"""Add screening questions and answers

Revision ID: 13a9dcd7debc
Revises: 7df621460ea6
Create Date: 2026-06-29 02:11:14.438653
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '13a9dcd7debc'
down_revision = '7df621460ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('screening_answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
    op.drop_index(op.f('ix_applications_job_score'), table_name='applications')
    op.drop_constraint(op.f('uq_candidates_user_id'), 'candidates', type_='unique')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=True)
    op.add_column('jobs', sa.Column('screening_questions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'screening_questions')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_candidates_user_id'), 'candidates', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_applications_job_score'), 'applications', ['job_id', 'match_score'], unique=False)
    op.drop_column('applications', 'screening_answers')
    # ### end Alembic commands ###
