"""Add AI queue columns to AssessmentRecording

Revision ID: 89994bc88513
Revises: 90fc54c77510
Create Date: 2026-06-30 01:50:02.652519
"""
from alembic import op
import sqlalchemy as sa


revision = '89994bc88513'
down_revision = '90fc54c77510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_recordings', sa.Column('ai_status', sa.String(length=20), nullable=True))
    op.add_column('assessment_recordings', sa.Column('ai_retry_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessment_recordings', sa.Column('ai_retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_assessment_recordings_ai_status'), 'assessment_recordings', ['ai_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_recordings_ai_status'), table_name='assessment_recordings')
    op.drop_column('assessment_recordings', 'ai_retry_count')
    op.drop_column('assessment_recordings', 'ai_retry_after')
    op.drop_column('assessment_recordings', 'ai_status')
    # ### end Alembic commands ###
