"""Add ai tracking fields to Application

Revision ID: 90fc54c77510
Revises: b8ce7223458e
Create Date: 2026-06-30 01:16:48.295606
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '90fc54c77510'
down_revision = 'b8ce7223458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ai_status', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('ai_retry_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('ai_retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('applications', sa.Column('ai_status_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('applications', sa.Column('ai_input_hash', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('baseline_fit', sa.Float(), server_default='0', nullable=False))
    op.add_column('applications', sa.Column('final_fit', sa.Float(), server_default='0', nullable=False))
    op.create_index(op.f('ix_applications_ai_input_hash'), 'applications', ['ai_input_hash'], unique=False)
    op.create_index(op.f('ix_applications_ai_status'), 'applications', ['ai_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_ai_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_ai_input_hash'), table_name='applications')
    op.drop_column('applications', 'final_fit')
    op.drop_column('applications', 'baseline_fit')
    op.drop_column('applications', 'ai_input_hash')
    op.drop_column('applications', 'ai_status_metadata')
    op.drop_column('applications', 'ai_retry_count')
    op.drop_column('applications', 'ai_retry_after')
    op.drop_column('applications', 'ai_status')
    # ### end Alembic commands ###
