"""Add job status

Revision ID: c3b7adeb2532
Revises: 0007_add_composite_ranking
Create Date: 2026-06-29 01:19:31.469796
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c3b7adeb2532'
down_revision = '0007_add_composite_ranking'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
